name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test:ci

      - name: Build
        run: yarn build
